### ISSUE TITLE
Pallette Command "Preference Helper: Switch User/Default.sublime-settings" does not work in ST2

### ISSUE THREAD

**Issue by twolfson** [csch0/SublimeText-Preference-Helper#1]
When I open the command pallette and use "Preference Helper: Switch User/Default.sublime-settings", nothing happens. I am guessing the command never got updated.

Also, for what it's worth, I would strongly appreciate namespaced commands (e.g. `pref_helper_toggle_file`) to avoid any potential conflicts with other plugins.

**Comment by csch0** [comment]
Agree with the prefix!! Will check the other issue!
